/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as UsuariosRouteImport } from "./routes/usuarios"
import { Route as ProntuariosRouteImport } from "./routes/prontuarios"
import { Route as PrescricoesRouteImport } from "./routes/prescricoes"
import { Route as PacientesRouteImport } from "./routes/pacientes"
import { Route as ExerciciosRouteImport } from "./routes/exercicios"
import { Route as ConfiguracoesRouteImport } from "./routes/configuracoes"
import { Route as AniversariosRouteImport } from "./routes/aniversarios"
import { Route as AgendaRouteImport } from "./routes/agenda"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PrescricoesNovaRouteImport } from "./routes/prescricoes.nova"
import { Route as PrescricoesIdRouteImport } from "./routes/prescricoes.$id"
import { Route as PacientesNovoRouteImport } from "./routes/pacientes.novo"
import { Route as PacientesIdRouteImport } from "./routes/pacientes.$id"
import { Route as ExerciciosNovoRouteImport } from "./routes/exercicios.novo"
import { Route as ExerciciosIdRouteImport } from "./routes/exercicios.$id"
import { Route as AuthRegisterRouteImport } from "./routes/auth/register"
import { Route as AuthRecoverPasswordRouteImport } from "./routes/auth/recover-password"
import { Route as AuthLoginRouteImport } from "./routes/auth/login"
import { Route as PacientesIdEditarRouteImport } from "./routes/pacientes.$id.editar"

const UsuariosRoute = UsuariosRouteImport.update({
  id: "/usuarios",
  path: "/usuarios",
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuariosRoute = ProntuariosRouteImport.update({
  id: "/prontuarios",
  path: "/prontuarios",
  getParentRoute: () => rootRouteImport,
} as any)
const PrescricoesRoute = PrescricoesRouteImport.update({
  id: "/prescricoes",
  path: "/prescricoes",
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: "/pacientes",
  path: "/pacientes",
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: "/exercicios",
  path: "/exercicios",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: "/configuracoes",
  path: "/configuracoes",
  getParentRoute: () => rootRouteImport,
} as any)
const AniversariosRoute = AniversariosRouteImport.update({
  id: "/aniversarios",
  path: "/aniversarios",
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: "/agenda",
  path: "/agenda",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PrescricoesNovaRoute = PrescricoesNovaRouteImport.update({
  id: "/nova",
  path: "/nova",
  getParentRoute: () => PrescricoesRoute,
} as any)
const PrescricoesIdRoute = PrescricoesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => PrescricoesRoute,
} as any)
const PacientesNovoRoute = PacientesNovoRouteImport.update({
  id: "/novo",
  path: "/novo",
  getParentRoute: () => PacientesRoute,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => PacientesRoute,
} as any)
const ExerciciosNovoRoute = ExerciciosNovoRouteImport.update({
  id: "/novo",
  path: "/novo",
  getParentRoute: () => ExerciciosRoute,
} as any)
const ExerciciosIdRoute = ExerciciosIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ExerciciosRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: "/auth/recover-password",
  path: "/auth/recover-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdEditarRoute = PacientesIdEditarRouteImport.update({
  id: "/editar",
  path: "/editar",
  getParentRoute: () => PacientesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/agenda": typeof AgendaRoute
  "/aniversarios": typeof AniversariosRoute
  "/configuracoes": typeof ConfiguracoesRoute
  "/exercicios": typeof ExerciciosRouteWithChildren
  "/pacientes": typeof PacientesRouteWithChildren
  "/prescricoes": typeof PrescricoesRouteWithChildren
  "/prontuarios": typeof ProntuariosRoute
  "/usuarios": typeof UsuariosRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/recover-password": typeof AuthRecoverPasswordRoute
  "/auth/register": typeof AuthRegisterRoute
  "/exercicios/$id": typeof ExerciciosIdRoute
  "/exercicios/novo": typeof ExerciciosNovoRoute
  "/pacientes/$id": typeof PacientesIdRouteWithChildren
  "/pacientes/novo": typeof PacientesNovoRoute
  "/prescricoes/$id": typeof PrescricoesIdRoute
  "/prescricoes/nova": typeof PrescricoesNovaRoute
  "/pacientes/$id/editar": typeof PacientesIdEditarRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/agenda": typeof AgendaRoute
  "/aniversarios": typeof AniversariosRoute
  "/configuracoes": typeof ConfiguracoesRoute
  "/exercicios": typeof ExerciciosRouteWithChildren
  "/pacientes": typeof PacientesRouteWithChildren
  "/prescricoes": typeof PrescricoesRouteWithChildren
  "/prontuarios": typeof ProntuariosRoute
  "/usuarios": typeof UsuariosRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/recover-password": typeof AuthRecoverPasswordRoute
  "/auth/register": typeof AuthRegisterRoute
  "/exercicios/$id": typeof ExerciciosIdRoute
  "/exercicios/novo": typeof ExerciciosNovoRoute
  "/pacientes/$id": typeof PacientesIdRouteWithChildren
  "/pacientes/novo": typeof PacientesNovoRoute
  "/prescricoes/$id": typeof PrescricoesIdRoute
  "/prescricoes/nova": typeof PrescricoesNovaRoute
  "/pacientes/$id/editar": typeof PacientesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/agenda": typeof AgendaRoute
  "/aniversarios": typeof AniversariosRoute
  "/configuracoes": typeof ConfiguracoesRoute
  "/exercicios": typeof ExerciciosRouteWithChildren
  "/pacientes": typeof PacientesRouteWithChildren
  "/prescricoes": typeof PrescricoesRouteWithChildren
  "/prontuarios": typeof ProntuariosRoute
  "/usuarios": typeof UsuariosRoute
  "/auth/login": typeof AuthLoginRoute
  "/auth/recover-password": typeof AuthRecoverPasswordRoute
  "/auth/register": typeof AuthRegisterRoute
  "/exercicios/$id": typeof ExerciciosIdRoute
  "/exercicios/novo": typeof ExerciciosNovoRoute
  "/pacientes/$id": typeof PacientesIdRouteWithChildren
  "/pacientes/novo": typeof PacientesNovoRoute
  "/prescricoes/$id": typeof PrescricoesIdRoute
  "/prescricoes/nova": typeof PrescricoesNovaRoute
  "/pacientes/$id/editar": typeof PacientesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/agenda"
    | "/aniversarios"
    | "/configuracoes"
    | "/exercicios"
    | "/pacientes"
    | "/prescricoes"
    | "/prontuarios"
    | "/usuarios"
    | "/auth/login"
    | "/auth/recover-password"
    | "/auth/register"
    | "/exercicios/$id"
    | "/exercicios/novo"
    | "/pacientes/$id"
    | "/pacientes/novo"
    | "/prescricoes/$id"
    | "/prescricoes/nova"
    | "/pacientes/$id/editar"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/agenda"
    | "/aniversarios"
    | "/configuracoes"
    | "/exercicios"
    | "/pacientes"
    | "/prescricoes"
    | "/prontuarios"
    | "/usuarios"
    | "/auth/login"
    | "/auth/recover-password"
    | "/auth/register"
    | "/exercicios/$id"
    | "/exercicios/novo"
    | "/pacientes/$id"
    | "/pacientes/novo"
    | "/prescricoes/$id"
    | "/prescricoes/nova"
    | "/pacientes/$id/editar"
  id:
    | "__root__"
    | "/"
    | "/agenda"
    | "/aniversarios"
    | "/configuracoes"
    | "/exercicios"
    | "/pacientes"
    | "/prescricoes"
    | "/prontuarios"
    | "/usuarios"
    | "/auth/login"
    | "/auth/recover-password"
    | "/auth/register"
    | "/exercicios/$id"
    | "/exercicios/novo"
    | "/pacientes/$id"
    | "/pacientes/novo"
    | "/prescricoes/$id"
    | "/prescricoes/nova"
    | "/pacientes/$id/editar"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AniversariosRoute: typeof AniversariosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ExerciciosRoute: typeof ExerciciosRouteWithChildren
  PacientesRoute: typeof PacientesRouteWithChildren
  PrescricoesRoute: typeof PrescricoesRouteWithChildren
  ProntuariosRoute: typeof ProntuariosRoute
  UsuariosRoute: typeof UsuariosRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/usuarios": {
      id: "/usuarios"
      path: "/usuarios"
      fullPath: "/usuarios"
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/prontuarios": {
      id: "/prontuarios"
      path: "/prontuarios"
      fullPath: "/prontuarios"
      preLoaderRoute: typeof ProntuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/prescricoes": {
      id: "/prescricoes"
      path: "/prescricoes"
      fullPath: "/prescricoes"
      preLoaderRoute: typeof PrescricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pacientes": {
      id: "/pacientes"
      path: "/pacientes"
      fullPath: "/pacientes"
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/exercicios": {
      id: "/exercicios"
      path: "/exercicios"
      fullPath: "/exercicios"
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/configuracoes": {
      id: "/configuracoes"
      path: "/configuracoes"
      fullPath: "/configuracoes"
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/aniversarios": {
      id: "/aniversarios"
      path: "/aniversarios"
      fullPath: "/aniversarios"
      preLoaderRoute: typeof AniversariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/agenda": {
      id: "/agenda"
      path: "/agenda"
      fullPath: "/agenda"
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/prescricoes/nova": {
      id: "/prescricoes/nova"
      path: "/nova"
      fullPath: "/prescricoes/nova"
      preLoaderRoute: typeof PrescricoesNovaRouteImport
      parentRoute: typeof PrescricoesRoute
    }
    "/prescricoes/$id": {
      id: "/prescricoes/$id"
      path: "/$id"
      fullPath: "/prescricoes/$id"
      preLoaderRoute: typeof PrescricoesIdRouteImport
      parentRoute: typeof PrescricoesRoute
    }
    "/pacientes/novo": {
      id: "/pacientes/novo"
      path: "/novo"
      fullPath: "/pacientes/novo"
      preLoaderRoute: typeof PacientesNovoRouteImport
      parentRoute: typeof PacientesRoute
    }
    "/pacientes/$id": {
      id: "/pacientes/$id"
      path: "/$id"
      fullPath: "/pacientes/$id"
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    "/exercicios/novo": {
      id: "/exercicios/novo"
      path: "/novo"
      fullPath: "/exercicios/novo"
      preLoaderRoute: typeof ExerciciosNovoRouteImport
      parentRoute: typeof ExerciciosRoute
    }
    "/exercicios/$id": {
      id: "/exercicios/$id"
      path: "/$id"
      fullPath: "/exercicios/$id"
      preLoaderRoute: typeof ExerciciosIdRouteImport
      parentRoute: typeof ExerciciosRoute
    }
    "/auth/register": {
      id: "/auth/register"
      path: "/auth/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/recover-password": {
      id: "/auth/recover-password"
      path: "/auth/recover-password"
      fullPath: "/auth/recover-password"
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth/login": {
      id: "/auth/login"
      path: "/auth/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pacientes/$id/editar": {
      id: "/pacientes/$id/editar"
      path: "/editar"
      fullPath: "/pacientes/$id/editar"
      preLoaderRoute: typeof PacientesIdEditarRouteImport
      parentRoute: typeof PacientesIdRoute
    }
  }
}

interface ExerciciosRouteChildren {
  ExerciciosIdRoute: typeof ExerciciosIdRoute
  ExerciciosNovoRoute: typeof ExerciciosNovoRoute
}

const ExerciciosRouteChildren: ExerciciosRouteChildren = {
  ExerciciosIdRoute: ExerciciosIdRoute,
  ExerciciosNovoRoute: ExerciciosNovoRoute,
}

const ExerciciosRouteWithChildren = ExerciciosRoute._addFileChildren(
  ExerciciosRouteChildren,
)

interface PacientesIdRouteChildren {
  PacientesIdEditarRoute: typeof PacientesIdEditarRoute
}

const PacientesIdRouteChildren: PacientesIdRouteChildren = {
  PacientesIdEditarRoute: PacientesIdEditarRoute,
}

const PacientesIdRouteWithChildren = PacientesIdRoute._addFileChildren(
  PacientesIdRouteChildren,
)

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRouteWithChildren
  PacientesNovoRoute: typeof PacientesNovoRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRouteWithChildren,
  PacientesNovoRoute: PacientesNovoRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

interface PrescricoesRouteChildren {
  PrescricoesIdRoute: typeof PrescricoesIdRoute
  PrescricoesNovaRoute: typeof PrescricoesNovaRoute
}

const PrescricoesRouteChildren: PrescricoesRouteChildren = {
  PrescricoesIdRoute: PrescricoesIdRoute,
  PrescricoesNovaRoute: PrescricoesNovaRoute,
}

const PrescricoesRouteWithChildren = PrescricoesRoute._addFileChildren(
  PrescricoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AniversariosRoute: AniversariosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ExerciciosRoute: ExerciciosRouteWithChildren,
  PacientesRoute: PacientesRouteWithChildren,
  PrescricoesRoute: PrescricoesRouteWithChildren,
  ProntuariosRoute: ProntuariosRoute,
  UsuariosRoute: UsuariosRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
